service: Golang-Serverless-API

framworkVersion: '>=1.28.0'

provider:
  name: aws
  runtime: go1.x
  region: us-east-1
  stage: ${opt:stage}

functions:
  handler: bin/main
  events: 
    - http:
        path: /ping
        method: GET

package:
  patterns:
#exclude 
    - '!*/**'

#include
    - bin/main